services:
  - type: web
    name: rag-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py master.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: OPEN_AI_TOKEN
        sync: false
      - key: JINA_TOKEN
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_HOST
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: GUNICORN_WORKERS
        value: 1
      - key: LOG_LEVEL
        value: info

